const pool = require('./models/db');
const Papa = require('papaparse');

// Mapping scientific names to S3 URLs
// const soundMap = {
//     'Syncerus caffer': 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/buffalo-syncerus-caffer.mp3',
//     'Papio anubis': 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/baboon-papio-anubis.mp3',
//     "Gorilla gorilla": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/gorilla-gorilla-beringei.mp3',
//     "Gorilla beringei": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/gorilla-gorilla-beringei.mp3',
//     "Pan paniscus": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/chimpanzee-pan-troglodytes.mp3',
//     "Hystrix cristata": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/porcupine-hystrix-cristata.mp3',
//     "Giraffa camelopardalis": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/giraffe-giraffa+camelopardalis.mp3',
//     "Acinonyx jubatus": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/cheetah-acinonyx-jubatus.mp3',
//     "Panthera pardus": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/leopard-panthera-pardus.mp3',
//     "Panthera leo": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/lion-panthera-leo.mp3',
//     "Loxodonta africana": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/elephant-loxodonta-africana.mp3',
//     "Loxodonta cyclotis": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/elephant-loxodonta-africana.mp3',
//     "Connochaetes taurinus": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/wildebeest-connochaetes-taurinus.mp3',
//     "Hippopotamus amphibius": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/hippopotamus-hippopotamus-amphibius.mp3',
//     "Crocuta crocuta": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/hyena-crocuta-crocuta.mp3',
//     "Ceratotherium simum": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/rhinoceros-ceratotherium-simum.mp3',
//     "Diceros bicornis": 'https://wildpedis-animal-sound.s3.us-east-1.amazonaws.com/animal_sound_dataset/rhinoceros-diceros-bicornis.mp3',
// };

// CSV data embedded within the script
const csvData = `
id,composite_key,gbif_key,scientific_name,vernacular_names,kingdom,kingdom_key,phylum,phylum_key,class,class_key,order_name,order_key,family,family_key,genus,genus_key,specific_epithet,taxonomic_status,nomenclatural_status,habitat,threat_status,description,image_url,image_source,created_at,last_modified
400,5219404_1_359,5219404,Loxodonta africana,"{""African Elephant"", African Bush Elephant, Savanna Elephant}",Animalia,1,Chordata,44,Mammalia,359,Proboscidea,1829,Elephantidae,7978,Loxodonta,2439365,africana,ACCEPTED,{},Savanna woodlands and grasslands across sub-Saharan Africa,Endangered (EN),"The largest living terrestrial animal characterized by its large ears, long trunk, and curved tusks. Adults reach shoulder heights of up to 4 meters and weights of 6-7 tons. Highly intelligent and social, they live in matriarchal family groups. Their diet consists primarily of grasses, fruits, bark, and roots.",https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/An_elephant_in_Kruger_National_Park.jpg/1920px-An_elephant_in_Kruger_National_Park.jpg,iNaturalist,2025-03-06 2:10:00,2025-03-06 2:10:00
401,5219427_1_359,5219427,Loxodonta cyclotis,"{""African Forest Elephant""}",Animalia,1,Chordata,44,Mammalia,359,Proboscidea,1829,Elephantidae,7978,Loxodonta,2439365,cyclotis,ACCEPTED,{},Dense rainforests of the Congo Basin and West Africa,Critically Endangered (CR),"A smaller and more elusive forest-dwelling elephant with rounder ears, straighter and downward-pointing tusks, and darker skin than savanna elephants. Forest elephants typically reach 2.5-3 meters in height. They play a crucial role in forest ecology through seed dispersal and creating forest clearings.",https://cdn.britannica.com/05/152305-050-0E7CC0FC/African-savanna-elephant-Botswana.jpg,iNaturalist,2025-03-06 2:10:10,2025-03-06 2:10:10
402,5218799_1_359,5218799,Panthera leo,"{""Lion"", African Lion}",Animalia,1,Chordata,44,Mammalia,359,Carnivora,732,Felidae,9703,Panthera,2435528,leo,ACCEPTED,{},Savanna grasslands and open woodlands across sub-Saharan Africa,Vulnerable (VU),The second-largest living cat species and the only social big cat. Males are distinguished by their impressive manes and can weigh up to 225 kg. Lions live in prides consisting of related females and their cubs with one or more males. They primarily hunt medium to large ungulates and have a distinctive tan coat with solid coloration.,https://cdn.britannica.com/29/150929-050-547070A1/lion-Kenya-Masai-Mara-National-Reserve.jpg,iNaturalist,2025-03-06 2:10:20,2025-03-06 2:10:20
403,5218752_1_359,5218752,Panthera pardus,"{""Leopard"", African Leopard}",Animalia,1,Chordata,44,Mammalia,359,Carnivora,732,Felidae,9703,Panthera,2435528,pardus,ACCEPTED,{},"Diverse habitats including forests, mountains, grasslands, and deserts across Africa",Vulnerable (VU),A solitary and adaptable big cat with a distinctive golden coat covered in dark rosette patterns. Leopards are excellent climbers and often hoist prey into trees to avoid scavengers. They weigh 40-90 kg and hunt primarily at night. Their adaptability allows them to survive in a wider range of habitats than other big cats.,https://cdn.britannica.com/41/146341-050-B49C48EE/Leopard-cub-Kenya-Masai-Mara-National-Reserve.jpg,iNaturalist,2025-03-06 2:10:30,2025-03-06 2:10:30
404,5218744_1_359,5218744,Acinonyx jubatus,"{""Cheetah""}",Animalia,1,Chordata,44,Mammalia,359,Carnivora,732,Felidae,9703,Acinonyx,2435492,jubatus,ACCEPTED,{},Open grasslands and savanna plains of Eastern and Southern Africa,Vulnerable (VU),"The world's fastest land animal, reaching speeds up to 110 km/h in short bursts. Cheetahs have a slender build, distinctive black tear marks running from the eyes to the mouth, and a tan coat covered with small solid black spots. Their specialized adaptations for speed include a flexible spine, semi-retractable claws, and enlarged heart and lungs.",https://cdn.britannica.com/99/152299-050-F7A06D34/Cheetah.jpg,iNaturalist,2025-03-06 2:10:40,2025-03-06 2:10:40
405,5481342_1_359,5481342,Ceratotherium simum,"{""White Rhinoceros"", Square-lipped Rhinoceros}",Animalia,1,Chordata,44,Mammalia,359,Perissodactyla,1839,Rhinocerotidae,9973,Ceratotherium,2440671,simum,ACCEPTED,{},Grasslands and savannas of Southern and Eastern Africa,Near Threatened (NT),"The largest rhinoceros species and the second-largest land mammal after elephants. Despite its name, the white rhino is gray in color. It has a distinctive wide, square upper lip adapted for grazing on grasses. Adults weigh 1800-2500 kg and have two horns on the snout with the front horn being larger than the rear one.",https://cdn.britannica.com/99/92699-050-26972485/White-rhinoceros-Mkuze-Game-Reserve-South-Africa.jpg,iNaturalist,2025-03-06 2:10:50,2025-03-06 2:10:50
406,5481346_1_359,5481346,Diceros bicornis,"{""Black Rhinoceros"", Hook-lipped Rhinoceros}",Animalia,1,Chordata,44,Mammalia,359,Perissodactyla,1839,Rhinocerotidae,9973,Diceros,2440674,bicornis,ACCEPTED,{},Savanna woodlands and shrublands across Eastern and Southern Africa,Critically Endangered (CR),A browser with a hooked upper lip adapted for feeding on leaves and twigs. It is smaller than the white rhino and has a more aggressive temperament. Black rhinos weigh 800-1400 kg and have two horns with the front horn typically being longer. Their population has been severely reduced by poaching for their horns.,https://cdn.britannica.com/89/162189-050-9CFBC925/Kavango-Zambezi-Transfrontier-Conservation-Area-rhino-species-March-2012.jpg,iNaturalist,2025-03-06 2:11:00,2025-03-06 2:11:00
407,5220026_1_359,5220026,Syncerus caffer,"{""African Buffalo"", Cape Buffalo}",Animalia,1,Chordata,44,Mammalia,359,Artiodactyla,1825,Bovidae,9895,Syncerus,2441175,caffer,ACCEPTED,{},"Savannas, grasslands, and forests across sub-Saharan Africa",Least Concern (LC),"A large robust bovine with fused horn bases forming a continuous shield (boss) across the forehead in males. Adults weigh 500-900 kg and are known for their unpredictable and sometimes aggressive behavior. African buffaloes form large herds and are one of the ""Big Five"" game animals. They are heavily dependent on water and typically stay within 20 km of a water source.",https://cdn.britannica.com/30/172430-050-FB535085/oxpecker-Cape-buffalo.jpg,iNaturalist,2025-03-06 2:11:10,2025-03-06 2:11:10
408,2440946_1_359,2440946,Giraffa camelopardalis,"{""Giraffe""}",Animalia,1,Chordata,44,Mammalia,359,Artiodactyla,1825,Giraffidae,5307,Giraffa,2440945,camelopardalis,ACCEPTED,{},"Savannas, woodlands and open grasslands with scattered trees across sub-Saharan Africa",Vulnerable (VU),"The tallest living terrestrial animal, with males reaching heights up to 5.5 meters. Giraffes have a distinctive spotted coat pattern that varies among subspecies and a long neck comprising just seven elongated vertebrae. Their specialized cardiovascular system maintains blood pressure to the brain despite the height difference. They feed primarily on acacia leaves and use their long, prehensile tongue to gather foliage.",https://cdn.britannica.com/06/92706-050-98CF9F28/Giraffes.jpg,iNaturalist,2025-03-06 2:11:20,2025-03-06 2:11:20
409,5220034_1_359,5220034,Hippopotamus amphibius,"{""Hippopotamus"", Common Hippopotamus, River Hippopotamus}",Animalia,1,Chordata,44,Mammalia,359,Artiodactyla,1825,Hippopotamidae,9917,Hippopotamus,2440986,amphibius,ACCEPTED,{},"Rivers, lakes, and wetlands across sub-Saharan Africa",Vulnerable (VU),"A massive semi-aquatic mammal that spends most daylight hours submerged in water to stay cool and protect its sensitive skin from the sun. Adults weigh 1500-3200 kg and are the third-largest land mammal. Despite their bulky appearance, they can run up to 30 km/h on land. Hippos are highly territorial in water and are considered one of Africa's most dangerous animals.",https://cdn.britannica.com/09/264209-050-DC6D646A/Hippopotamus-herd-Water-hole-Botswana-Africa-hippos.jpg,iNaturalist,2025-03-06 2:11:30,2025-03-06 2:11:30
410,5220063_1_359,5220063,Crocuta crocuta,"{""Spotted Hyena"", Laughing Hyena}",Animalia,1,Chordata,44,Mammalia,359,Carnivora,732,Hyaenidae,9726,Crocuta,2434427,crocuta,ACCEPTED,{},"Savannas, grasslands, woodlands and semi-desert across sub-Saharan Africa",Least Concern (LC),The largest member of the hyena family characterized by its spotted coat sloping back and powerful jaws capable of crushing bone. Contrary to popular belief they are not primarily scavengers but skilled hunters that obtain up to 80% of their food through predation. Spotted hyenas live in complex social groups called clans led by dominant females who are larger than males.,https://cdn.britannica.com/28/130028-050-4CDC40C6/Hyena.jpg,iNaturalist,2025-03-06 2:11:40,2025-03-06 2:11:40
411,8659814_1_359,8659814,Kobus ellipsiprymnus,"{""Waterbuck""}",Animalia,1,Chordata,44,Mammalia,359,Artiodactyla,1825,Bovidae,9895,Kobus,2441019,ellipsiprymnus,ACCEPTED,{},Savanna grasslands and forests near water sources across sub-Saharan Africa,Least Concern (LC),"A large antelope species with a shaggy coat, distinctive beard and curved horns in both sexes. Known for their annual mass migrations in search of fresh grazing and water. Adults weigh 180-250 kg and have a blue-gray coat with darker vertical stripes on the forequarters. They form large herds that can number in the thousands during migration periods.",https://cdn.britannica.com/24/128424-050-82746346/waterbuck.jpg,iNaturalist,2025-03-06 2:11:50,2025-03-06 2:11:50
412,5220013_1_359,5220013,Connochaetes taurinus,"{""Blue Wildebeest"", Brindled Gnu}",Animalia,1,Chordata,44,Mammalia,359,Artiodactyla,1825,Bovidae,9895,Connochaetes,2441008,taurinus,ACCEPTED,{},Open grasslands and savannas of Eastern and Southern Africa,Least Concern (LC),A large antelope with a bovine-like head distinctive beard and curved horns in both sexes. Known for their annual mass migrations in search of fresh grazing and water. Adults weigh 180-250 kg and have a blue-gray coat with darker vertical stripes on the forequarters. They form large herds that can number in the thousands during migration periods.,https://cdn.britannica.com/92/150292-050-3A539C17/herd-wildebeest-keystone-species-savanna-Africa-plains.jpg,iNaturalist,2025-03-06 2:12:00,2025-03-06 2:12:00
413,2436246_1_359,2436246,Gorilla gorilla,"{""Western Gorilla"", Lowland Gorilla}",Animalia,1,Chordata,44,Mammalia,359,Primates,798,Hominidae,9604,Gorilla,2436245,gorilla,ACCEPTED,{},Tropical and subtropical forest habitats of Central and West Africa,Critically Endangered (CR),"The largest living primate with males weighing up to 180 kg. Characterized by a broad chest, large head and black/brown hair. Western gorillas have a more brownish-gray coat than eastern gorillas. They live in groups led by a dominant silverback male and feed primarily on vegetation. Despite their intimidating appearance they have gentle dispositions and complex social structures.",https://cdn.britannica.com/64/65364-050-53E75D82/lowland-gorilla.jpg,iNaturalist,2025-03-06 2:12:10,2025-03-06 2:12:10
414,2436448_1_359,2436448,Gorilla beringei,"{""Eastern Gorilla"", Mountain Gorilla}",Animalia,1,Chordata,44,Mammalia,359,Primates,798,Hominidae,9604,Gorilla,2436245,beringei,ACCEPTED,{},Montane forests of the Albertine Rift in Eastern Africa,Critically Endangered (CR),The largest of the gorilla subspecies with longer and darker fur adapted to colder montane habitats. Adult males can weigh up to 200 kg and develop a distinctive silvery saddle across their back with maturity. They live in stable family groups led by a dominant silverback male and feed almost exclusively on vegetation. Mountain gorillas share about 98% of their DNA with humans.,https://cdn.britannica.com/79/20279-050-ECDF21A7/mountain-gorilla-Virunga-National-Park-Democratic-Republic.jpg,iNaturalist,2025-03-06 2:12:20,2025-03-06 2:12:20
415,4781458_1_359,4781458,Pan troglodytes,"{""Common Chimpanzee"", Robust Chimpanzee}",Animalia,1,Chordata,44,Mammalia,359,Primates,798,Hominidae,9604,Pan,2436432,troglodytes,ACCEPTED,{},Tropical forests and savannas across Central and West Africa,Endangered (EN),"Our closest living relative sharing approximately 98.8% of our DNA. Chimpanzees have a robust build, black hair and nearly hairless faces that darken with age. They are highly intelligent, use tools and have complex social structures. Adults weigh 40-70 kg and are primarily frugivorous although they occasionally hunt small mammals. Different chimpanzee communities develop distinctive cultural behaviors and tool use traditions.",https://cdn.britannica.com/70/189070-050-A3AF510B/Chimpanzees-ground-trees-branch-swing-arms-distance.jpg,iNaturalist,2025-03-06 2:12:30,2025-03-06 2:12:30
416,2436251_1_359,2436251,Pan paniscus,"{""Bonobo"", Pygmy Chimpanzee}",Animalia,1,Chordata,44,Mammalia,359,Primates,798,Hominidae,9604,Pan,2436432,paniscus,ACCEPTED,{},Lowland rainforests of the Democratic Republic of the Congo south of the Congo River,Endangered (EN),"A smaller and more gracile cousin of the chimpanzee with longer legs, pink lips, a center hair part and a more rounded skull. Bonobos have a matriarchal social structure and are famous for resolving conflicts through sexual behavior rather than aggression. They weigh 34-60 kg and feed primarily on fruits though they also consume other plant parts and occasionally small animals.",https://cdn.britannica.com/55/93255-050-F40248EA/Bonobo-sanctuary-Republic-of-the-Congo.jpg,iNaturalist,2025-03-06 2:12:40,2025-03-06 2:12:40
417,5708952_1_359,5708952,Papio anubis,"{""Olive Baboon""}",Animalia,1,Chordata,44,Mammalia,359,Primates,798,Cercopithecidae,9528,Papio,2436386,anubis,ACCEPTED,{},Savanna and woodland habitats across equatorial Africa,Least Concern (LC),"A large terrestrial monkey with an olive-green coat and a dog-like muzzle. Males are significantly larger than females (20-50 kg vs. 10-25 kg) and have longer canine teeth. Olive baboons live in multi-male multi-female troops of 15-150 individuals with a complex social hierarchy. They are opportunistic omnivores consuming fruits, seeds, roots, leaves, invertebrates, and occasionally small vertebrates.",https://cdn.britannica.com/65/188565-050-7BAAF99E/Yellow-baboon-mother-baby-back-Malawi-Primate.jpg,iNaturalist,2025-03-06 2:12:50,2025-03-06 2:12:50
418,2437933_1_359,2437933,Hystrix cristata,"{""North African Crested Porcupine""}",Animalia,1,Chordata,44,Mammalia,359,Rodentia,1459,Hystricidae,10014,Hystrix,2437932,cristata,ACCEPTED,{},"Various habitats including forests, grasslands, and rocky areas across North and West Africa",Least Concern (LC),"One of the largest rodents in Africa, weighing up to 27 kg. Its most distinctive feature is the impressive crest of long quills that can be raised as a defensive display. The body is covered with shorter quills that detach easily when touched and can cause painful injuries to predators. This primarily nocturnal species feeds on roots, bulbs fruits and farm crops and lives in family groups in burrows or caves.",https://cdn.britannica.com/16/93516-050-3FB4ABE4/Cape-porcupine.jpg,iNaturalist,2025-03-06 2:13:00,2025-03-06 2:13:00
419,2436124_1_359,2436124,Smutsia gigantea,"{""Giant Ground Pangolin""}",Animalia,1,Chordata,44,Mammalia,359,Pholidota,1454,Manidae,9934,Smutsia,2436123,gigantea,ACCEPTED,{},Savanna woodlands and forests of Central and West Africa,Endangered (EN),The largest pangolin species reaching up to 1.8 meters in length and weighing up to 33 kg. Its body is covered with large overlapping scales made of keratin (the same material as human fingernails). When threatened pangolins roll into a tight ball and use their sharp-edged scales for protection. They are specialized myrmecophages feeding exclusively on ants and termites which they extract using their long sticky tongues.,https://cdn.britannica.com/41/124241-050-9027A8EF/Pangolin.jpg,iNaturalist,2025-03-06 2:13:10,2025-03-06 2:13:10
420,2436883_1_359,2436883,Lycaon pictus,"{""African Wild Dog"", Painted Wolf, African Hunting Dog}",Animalia,1,Chordata,44,Mammalia,359,Carnivora,732,Canidae,9609,Lycaon,2436882,pictus,ACCEPTED,{},Savanna and arid zones across sub-Saharan Africa,Endangered (EN),A highly social canid with a distinctive mottled coat pattern of black brown yellow and white with each individual having a unique pattern. Adults weigh 20-30 kg. Wild dogs live in packs of 6-20 individuals with a complex social hierarchy. They are among Africa's most efficient hunters with a success rate of around 80%. The pack hunts cooperatively and shares food prioritizing feeding pups and sick members.,https://cdn.britannica.com/31/169531-050-754E60E1/African-wild-dogs-Kruger-National-Park-South.jpg,iNaturalist,2025-03-06 2:13:20,2025-03-06 2:13:20
`;

async function importData() {
    // Parse the CSV data
    const results = Papa.parse(csvData, { header: true, skipEmptyLines: true });
    const data = results.data;

    // Define fields that should be integers
    const integerFields = ['id', 'gbif_key', 'kingdom_key', 'phylum_key', 'class_key', 'order_key', 'family_key', 'genus_key'];

    // Define all columns, including sound_url
    const columns = [
        'id', 'composite_key', 'gbif_key', 'scientific_name', 'vernacular_names',
        'kingdom', 'kingdom_key', 'phylum', 'phylum_key', 'class', 'class_key',
        'order_name', 'order_key', 'family', 'family_key', 'genus', 'genus_key',
        'specific_epithet', 'taxonomic_status', 'nomenclatural_status', 'habitat',
        'threat_status', 'description', 'image_url', 'image_source', 'created_at',
        'last_modified', 'sound_url'
    ];

    // Iterate over each row and insert into the database
    for (const row of data) {
        const values = columns.map(col => {
            if (row[col] === undefined || row[col] === '') {
                return null; // Handle missing or empty fields
            } else if (integerFields.includes(col)) {
                const val = parseInt(row[col]);
                return isNaN(val) ? null : val; // Convert to integer or null if invalid
            } else if (col === 'sound_url') {
                return soundMap[row.scientific_name] || null; // Set sound_url from soundMap
            } else {
                return row[col]; // Use value as is (text, timestamp, etc.)
            }
        });

        try {
            await pool.query(`
                INSERT INTO species (${columns.join(', ')})
                VALUES (${columns.map((_, i) => `$${i + 1}`).join(', ')})
            `, values);
            console.log(`Inserted ${row.scientific_name}`);
        } catch (err) {
            console.error(`Error inserting ${row.scientific_name}:`, err);
        }
    }
}

// Run the import function
importData()
    .then(() => console.log('Data import complete'))
    .catch(err => console.error('Error during import:', err))
    .finally(() => pool.end());